### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'upper' in __sub_wessim1.py

### ISSUE THREAD

**Issue by cluhaowie** [YJulyXing/SECNVs#1]
The error occurs every time I run the simulation. The error seems not effecting every  subprocess, some subprocess is able to finish the run. 
Here is the code I ran
python ~/SECNVs/SECNVs.py 
-G GRCh38_full_analysis_set_plus_decoy_hla.fa 
-T crome2.1_core_hg38_no_name.bed 
-eN gap -n_gap 50 -e_tol 100 -min_len 100 -max_len 100000 -min_cn 2 -max_cn 6 -ssr -l 100 -pr -sb -nr 400000 
-o imulation -n 1 -picard picard -GATK gatk-4.1.3.0 > log.file 2>&1

error message:

exiting subprocess 3
unexpected stop
Traceback (most recent call last):
  File "__sub_wessim1.py", line 832, in <module>
    main(sys.argv[1:])
  File "__sub_wessim1.py", line 232, in main
    wread.write(read1.upper()+'\n')
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by awast** [comment]
Hi ,
    I am also getting the same error . If you resolved this issue please do share it will be great help
